### ISSUE TITLE
Error resolving target specification '' (No targets match target specification), specified in query 'GPUCurrentFanSpeedRPM'

### ISSUE THREAD

**Issue by ghost** [vandabbin/nvidia-fan-control-linux#1]
When running fan-control info I get the following error: 

ERROR: Error resolving target specification '' (No targets match target
       specification), specified in query 'GPUCurrentFanSpeedRPM'.

and the info given is the following. Changin of the 
| Card |		                     | Fan Speed |	| Fan RPM |	| GPU Temp |
0: GeForce GTX 1060	     [Not%	                      46	     °

My 10-nvidia.conf file contains the following

Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "AllowEmptyInitialConfiguration"
    Option "Coolbits" "31"
    ModulePath "/usr/lib/x86_64-linux-gnu/nvidia-418/xorg"
EndSection

**Comment by vandabbin** [comment]
Interesting. 

What output do you get if you run `nvidia-settings -q :0/GPUCurrentFanSpeedRPM` and `nvidia-settings -q all | grep -i fan`

I will do some testing with different driver versions and see if I can replicate your issue

**Comment by vandabbin** [comment]
While I am figuring out how to solve that issue I created a temporary bugfix branch. Use that one instead and it should just output N/A for fan rpm if it runs into that error. When I figure out why that error is occuring. most likely a driver thing. then I will update the master branch with a good fix
https://github.com/vandabbin/nvidia-fan-control-linux/tree/bugfix

**Comment by vandabbin** [comment]
@mads0109 Can you also give me the output of `nvidia-smi --query-gpu=fan.speed --format=csv` and
`nvidia-smi`

**Comment by ghost** [comment]
nvidia-smi --query-gpu=fan.speed --format=csv gives the result: 
fan.speed [%]
[Not Supported]

So my bad, I guess I can't controll the fan speed

**Comment by vandabbin** [comment]
@mads0109 Maybe try coolbits 28 instead of 31 and see if that helps at all?
