### ISSUE TITLE
What minimal requirement for CLI interface? (No GUI)

### ISSUE THREAD

**Issue by minzak** [vandabbin/nvidia-fan-control-linux#2]
Hm, how to be, if i not have GUI?

```
nvidia-settings

ERROR: libgtk-3.so.0: cannot open shared object file: No such file or directory
       libnvidia-gtk3.so: cannot open shared object file: No such file or directory
       libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
       libnvidia-gtk2.so: cannot open shared object file: No such file or directory


ERROR: A problem occured when loading the GUI library. Please check your installation and library path. You may need to specify this library when calling nvidia-settings. Please run
       `nvidia-settings --help` for usage information.
```

What minimum packet must install to use fancontrol without GUI?

**Comment by vandabbin** [comment]
I appreciate you opening this issue. I didn't even realize this was occurring. I will work on figuring out a solution.

**Comment by vandabbin** [comment]
I have looked into a work around to allow setting fan speed on an nvidia gpu without an X server running and the only workaround seems to be to start an X server and configure your xorg.conf to have a dummy display. Nvidia's drivers don't allow for setting fan speed without an X server though
