### ISSUE TITLE
Question: update frequency

### ISSUE THREAD

**Issue by alexbogun** [vandabbin/nvidia-fan-control-linux#3]
Hi, this is a question, not an issue.

I would like to control the fan curve of my GPU used for deep learning, and your script looks great for that, but I think the default update of once in 30 seconds would not be enough. Is there any downside to setting it to 1 sec? What I mean do you know if there is a big overhead in querying GPU temperature so frequently?

Thanks in advance
Alex

**Comment by vandabbin** [comment]
I haven't done a lot of testing on that. I have timed how long it takes to query the gpu temp and fan speed and then apply a new fan speed using the time command. It seems to take approximately .7 seconds to query and .6 seconds to set fan temp. I just tried running it in a while loop with no sleep interval and the timing is staying pretty consistent. Occasionally a query seems to take a bit longer though. I think 2 seconds is probably a better interval for that reason. I also didn't observe any drop in gpu performance while testing and the gpus and CPU were at 100% usage running mining software. I hope that helps
![20210909_121109.jpg](https://user-images.githubusercontent.com/15382321/132748265-a4ff44fb-8603-4648-9025-cd82d96aa6ba.jpg)![20210909_121105.jpg](https://user-images.githubusercontent.com/15382321/132748252-e440ce8d-1e6d-47c0-844e-23912eae5783.jpg)

**Comment by alexbogun** [comment]
Thanks a lot for a quick reply and your time testing. Another question, I see you also use the machine via CLI, but my understanding is that nvidia-settings requires X-server running. Do you have a dummy one running?

**Comment by vandabbin** [comment]
Yes, that is correct that nvidia-settings requires an xserver. I personally have my system running a lightweight window manager i3wm and mostly just ssh into the system to manage it. A dummy xserver would be all you really need though

**Comment by alexbogun** [comment]
Thank you for your replies
